.TH METEORREWIND 3  2007-02-25 "Meteor Manpage"
.SH NAME
meteorRewind
.SH SYNOPSIS
.B #include <meteor.h>
.sp
.BI "void meteorRewind(void);"
.SH DESCRIPTION
This function rewinds the offsets used by \fBmeteorReadPoints\fP and
\fBmeteorReadTriangles\fP.
.SH NOTES
\fBmeteorReset\fP causes an implicit rewind.
.SH SEE ALSO
.BR meteor (1)
.BR meteorReset (3)
.BR meteorReadPoints (3)
.BR meteorReadTriangles (3)
